# Word Embedding Techniques using Embedding Layer in Keras

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

# Sentences

In [2]:
sent =["the glass of milk",
      "the glass of juice",
      "the cup of tea",
      "I am a good boy",
      "I am a good developer",
      "understands the meaning of words",
      "your videos are good"]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understands the meaning of words',
 'your videos are good']

In [4]:
#Vocabulary_size
voc_size=10000

# One_Hot_Representation


In [5]:
One_hot_rep = [one_hot(words, voc_size)for words in sent]
print(One_hot_rep)

[[6780, 3505, 9190, 246], [6780, 3505, 9190, 7428], [6780, 6171, 9190, 1007], [5949, 9983, 4156, 225, 1042], [5949, 9983, 4156, 225, 1937], [2153, 6780, 7091, 9190, 499], [4407, 6830, 1926, 225]]


# Word Embedding Representation

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs = pad_sequences(One_hot_rep, padding="pre", maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6780 3505 9190  246]
 [   0    0    0    0 6780 3505 9190 7428]
 [   0    0    0    0 6780 6171 9190 1007]
 [   0    0    0 5949 9983 4156  225 1042]
 [   0    0    0 5949 9983 4156  225 1937]
 [   0    0    0 2153 6780 7091 9190  499]
 [   0    0    0    0 4407 6830 1926  225]]


In [9]:
dim = 15

In [10]:
model=Sequential()
model.add(Embedding(voc_size, 10, input_length=sent_length))
model.compile("adam","mse")

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [12]:
print(model.predict(embedded_docs))

[[[ 4.62037809e-02  1.79874189e-02  2.19417475e-02  2.57053412e-02
    6.65346533e-03 -3.53705771e-02 -4.34990898e-02  4.23079990e-02
   -2.36133095e-02  1.50506161e-02]
  [ 4.62037809e-02  1.79874189e-02  2.19417475e-02  2.57053412e-02
    6.65346533e-03 -3.53705771e-02 -4.34990898e-02  4.23079990e-02
   -2.36133095e-02  1.50506161e-02]
  [ 4.62037809e-02  1.79874189e-02  2.19417475e-02  2.57053412e-02
    6.65346533e-03 -3.53705771e-02 -4.34990898e-02  4.23079990e-02
   -2.36133095e-02  1.50506161e-02]
  [ 4.62037809e-02  1.79874189e-02  2.19417475e-02  2.57053412e-02
    6.65346533e-03 -3.53705771e-02 -4.34990898e-02  4.23079990e-02
   -2.36133095e-02  1.50506161e-02]
  [-1.26565807e-02  1.16908662e-02  4.35504653e-02  1.62758119e-02
   -1.09107867e-02 -3.63754034e-02  3.70131023e-02 -3.75873558e-02
    4.67477180e-02  2.25383043e-03]
  [ 3.55101265e-02  3.76049988e-02  1.91842802e-02  3.78867239e-03
    3.84051912e-02  2.58417018e-02 -4.50239070e-02  9.19405371e-03
   -2.85486337e-

In [13]:
embedded_docs[0]

array([   0,    0,    0,    0, 6780, 3505, 9190,  246])

In [14]:
print(model.predict(embedded_docs)[0])

[[ 0.04620378  0.01798742  0.02194175  0.02570534  0.00665347 -0.03537058
  -0.04349909  0.042308   -0.02361331  0.01505062]
 [ 0.04620378  0.01798742  0.02194175  0.02570534  0.00665347 -0.03537058
  -0.04349909  0.042308   -0.02361331  0.01505062]
 [ 0.04620378  0.01798742  0.02194175  0.02570534  0.00665347 -0.03537058
  -0.04349909  0.042308   -0.02361331  0.01505062]
 [ 0.04620378  0.01798742  0.02194175  0.02570534  0.00665347 -0.03537058
  -0.04349909  0.042308   -0.02361331  0.01505062]
 [-0.01265658  0.01169087  0.04355047  0.01627581 -0.01091079 -0.0363754
   0.0370131  -0.03758736  0.04674772  0.00225383]
 [ 0.03551013  0.037605    0.01918428  0.00378867  0.03840519  0.0258417
  -0.04502391  0.00919405 -0.02854863 -0.02598577]
 [ 0.04884454  0.03570911  0.04989943 -0.04008551 -0.02126181  0.02665926
   0.03224606 -0.00091208  0.00951248 -0.04720151]
 [ 0.0008315   0.03020079 -0.03321823  0.0085287  -0.03257447 -0.02571125
   0.02739933 -0.00491757 -0.00693794  0.0020357 ]]
